sensor_kit_base_link:
  rs16:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  gnss:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
rs16:
  camera0:
    x: 0
    y: 0
    z: 0
    roll: 0
    pitch: 0
    yaw: 0
